### ISSUE TITLE
Restful한 설계를 잘 했나요?

### ISSUE THREAD

**Issue by minnieming** [Peter-Yu-0402/Hanghae99_Spring_03#2]
POST, 
PUT, 
GET을
 잘 사용을 했고, 

@PathVariable,
@RequestBody도 
잘 못 사용한것 없이 적절하게 잘 사용한것 같습니다!

**Comment by Peter-Yu-0402** [comment]
확인 감사합니다! :D

**Comment by devjsyu** [comment]
확인 감사합니다! :D
