### ISSUE TITLE
API 명세서에 따른 설계가 잘 되어있나요?

### ISSUE THREAD

**Issue by minnieming** [Peter-Yu-0402/Hanghae99_Spring_03#3]
🔍
선택한 강사가 촬영한 강의 목록 조회에 URL 경로가 달라요!

강의 등록할때 createdAt은 자동으로 생성일을 만드는 것 같은데, request는 클라이언트에게 요청받는 값이라서, response에만 넣으면 될 것 같습니다 (lectureId와 동일한 경우)

강의 등록하고 수정할때, createdAt과 modifiedAt이 response명세서에 있는데 responseDto에는 없어서 통일 하면 좋을 것 같습니다

👍🏻
관리자 가입 response에 role을 그냥 role로 표시 할 수도 있는데, MANAGER, STAFF라고 정확하게 명시한 점이 한번에 파악도 되는것 좋은것 같습니다.

로그인 response값에 HeaderKey를 넣은 것과 그 후의 requesta 값에 HeaderKey를 넣은것도  저는 생각을 못했던 부분인데 좋은것 같아요!

API 명세서의 response 부분에 tutorId, experienceYears 같은 부분은 예상 답변값을 넣으신 부분이 좋은것 같습니다.
강사가 촬영한 강의 목록 조회의 response값의 형식도 동일하게 하신것 같아서 보기 좋은것 같아요!

**Comment by devjsyu** [comment]
놓친 부분을 짚어주셔서 많이 배웠습니다
확인 감사합니다! :D
