### ISSUE TITLE
예외처리가 미흡한 부분은 없나요?

### ISSUE THREAD

**Issue by minnieming** [Peter-Yu-0402/Hanghae99_Spring_03#4]
예외처리는 잘 된 것 같습니다.

controller 부분에 따로 빼서 처리한 것도 좋았습니다!

예외처리를 아예 하나의 클래스를 만들어서 사용하기도 한다는데, 다음에 기회 되면 해보시는 것도 좋을 것 같습니다!

+
저는 User, Tutor, Lecture 이런식으로 나눠서 파일을 구성했는데, 
유형별로 나눠서 정리하니까 이렇게 하는 방법도 장점이 있는 것 같아서 좋았습니다

**Comment by devjsyu** [comment]
확인 감사합니다! :D
